Missing comma on tickscript.join - Fixed
Missing comma added on tickscript.join function.

If you `Inject` the function `tickscript.join` on the ui. You will get the next error:

```
compilation failed: error @19:6-23:2: expected comma in property list, got COLON

error @21:7-21:18: missing property key 
```